@startuml
digraph G {
1 -> 3 [label = 51]
1 -> 4 [label = 22]
1 -> 2 [label = 76]
2 -> 3 [label = 91]
2 -> 4 [label = 68]
3 -> 4 [label = 14]
4 -> 3 [label = 50]
4 -> 2 [label = 59]
4 -> 1 [label = 54]
4 -> 5 [label = 59]
5 -> 3 [label = 26]
5 -> 1 [label = 57]
5 -> 2 [label = 55]
}

@enduml